import jwt from 'jsonwebtoken';
import bcrypt from 'bcryptjs';
import { Request, Response, NextFunction } from 'express';

// JWT secret (should be in environment variable)
const JWT_SECRET = process.env.JWT_SECRET || 'your-super-secret-jwt-key-change-this-in-production';
const JWT_EXPIRES_IN = '7d'; // Token expires in 7 days

export interface JWTPayload {
  userId: string;
  email: string;
  role: string;
  vendorId?: string;
}

export interface AuthRequest extends Request {
  user?: JWTPayload;
}

/**
 * Generate JWT token
 */
export function generateToken(payload: JWTPayload): string {
  return jwt.sign(payload, JWT_SECRET, { expiresIn: JWT_EXPIRES_IN });
}

/**
 * Verify JWT token
 */
export function verifyToken(token: string): JWTPayload | null {
  try {
    const decoded = jwt.verify(token, JWT_SECRET) as JWTPayload;
    return decoded;
  } catch (error) {
    console.error('JWT verification failed:', error);
    return null;
  }
}

/**
 * Hash password
 */
export async function hashPassword(password: string): Promise<string> {
  const salt = await bcrypt.genSalt(10);
  return bcrypt.hash(password, salt);
}

/**
 * Compare password with hash
 */
export async function comparePassword(password: string, hash: string): Promise<boolean> {
  return bcrypt.compare(password, hash);
}

/**
 * Middleware to authenticate JWT token
 */
export function authenticateToken(req: AuthRequest, res: Response, next: NextFunction) {
  // Get token from Authorization header
  const authHeader = req.headers['authorization'];
  const token = authHeader && authHeader.split(' ')[1]; // Bearer TOKEN

  if (!token) {
    return res.status(401).json({ error: 'Access token required' });
  }

  const payload = verifyToken(token);
  
  if (!payload) {
    return res.status(403).json({ error: 'Invalid or expired token' });
  }

  req.user = payload;
  next();
}

/**
 * Optional authentication - doesn't fail if no token
 */
export function optionalAuth(req: AuthRequest, res: Response, next: NextFunction) {
  const authHeader = req.headers['authorization'];
  const token = authHeader && authHeader.split(' ')[1];

  if (token) {
    const payload = verifyToken(token);
    if (payload) {
      req.user = payload;
    }
  }

  next();
}

/**
 * Middleware to check user role
 */
export function requireRole(...roles: string[]) {
  return (req: AuthRequest, res: Response, next: NextFunction) => {
    if (!req.user) {
      return res.status(401).json({ error: 'Authentication required' });
    }

    if (!roles.includes(req.user.role)) {
      return res.status(403).json({ error: 'Insufficient permissions' });
    }

    next();
  };
}

/**
 * Sign up handler
 */
export async function signUp(req: Request, res: Response) {
  try {
    const { email, password, username, role = 'vendor' } = req.body;

    // Validate input
    if (!email || !password || !username) {
      return res.status(400).json({ error: 'Email, password, and username are required' });
    }

    if (password.length < 6) {
      return res.status(400).json({ error: 'Password must be at least 6 characters' });
    }

    // Import storage dynamically to avoid circular dependency
    const { storage } = await import('./storage');

    // Check if user already exists
    const existingUser = await storage.getUserByEmail(email.toLowerCase());
    
    if (existingUser) {
      return res.status(400).json({ error: 'User with this email already exists' });
    }

    // Hash password
    const passwordHash = await hashPassword(password);

    // Create user (ID will be auto-generated by storage)
    const user = await storage.createUser({
      email: email.toLowerCase(),
      username,
      role,
      passwordHash, // Store hashed password
    });

    // Generate JWT token
    const token = generateToken({
      userId: user.id,
      email: user.email,
      role: user.role,
    });

    console.log(`✅ [Auth] User registered: ${email} (${role})`);

    res.json({
      success: true,
      token,
      user: {
        id: user.id,
        email: user.email,
        username: user.username,
        role: user.role,
      },
    });
  } catch (error: any) {
    console.error('[Auth] Signup error:', error);
    res.status(500).json({ error: error.message || 'Failed to sign up' });
  }
}

/**
 * Sign in handler
 */
export async function signIn(req: Request, res: Response) {
  try {
    const { email, password } = req.body;

    // Validate input
    if (!email || !password) {
      return res.status(400).json({ error: 'Email and password are required' });
    }

    // Import storage dynamically
    const { storage } = await import('./storage');

    // Find user by email
    const user = await storage.getUserByEmail(email.toLowerCase());

    if (!user) {
      return res.status(401).json({ error: 'Invalid email or password' });
    }

    // Check if user has a password hash
    if (!user.passwordHash) {
      return res.status(401).json({ error: 'Account not set up properly. Please contact support.' });
    }

    // Verify password
    const isValidPassword = await comparePassword(password, user.passwordHash);

    if (!isValidPassword) {
      return res.status(401).json({ error: 'Invalid email or password' });
    }

    // Get vendor ID if user is a vendor
    let vendorId: string | undefined;
    if (user.role === 'vendor') {
      const vendor = await storage.getVendorByUserId(user.id);
      if (vendor) {
        vendorId = vendor.id;
      }
    }

    // Generate JWT token
    const token = generateToken({
      userId: user.id,
      email: user.email,
      role: user.role,
      vendorId,
    });

    console.log(`✅ [Auth] User logged in: ${email} (${user.role})`);

    res.json({
      success: true,
      token,
      user: {
        id: user.id,
        email: user.email,
        username: user.username,
        role: user.role,
        vendorId,
        modulePermissions: user.modulePermissions || [],
        name: (user as any).name,
        phone: (user as any).phone,
        department: (user as any).department,
        jobRole: (user as any).jobRole,
      },
    });
  } catch (error: any) {
    console.error('[Auth] Login error:', error);
    res.status(500).json({ error: error.message || 'Failed to sign in' });
  }
}

/**
 * Sign out handler
 */
export async function signOut(req: Request, res: Response) {
  // With JWT, we don't need to do anything on the server
  // The client just needs to delete the token
  res.json({ success: true, message: 'Signed out successfully' });
}

/**
 * Get current user handler
 */
export async function getCurrentUser(req: AuthRequest, res: Response) {
  try {
    if (!req.user) {
      return res.status(401).json({ error: 'Not authenticated' });
    }

    // Import storage dynamically
    const { storage } = await import('./storage');

    // Get full user details
    const user = await storage.getUser(req.user.userId);

    if (!user) {
      return res.status(404).json({ error: 'User not found' });
    }

    // Get vendor if user is a vendor
    let vendor = null;
    if (user.role === 'vendor') {
      vendor = await storage.getVendorByUserId(user.id);
    }

    res.json({
      user: {
        id: user.id,
        email: user.email,
        username: user.username,
        role: user.role,
      },
      vendor: vendor ? {
        id: vendor.id,
        businessName: vendor.businessName,
        ownerName: vendor.ownerName,
      } : null,
    });
  } catch (error: any) {
    console.error('[Auth] Get current user error:', error);
    res.status(500).json({ error: error.message || 'Failed to get current user' });
  }
}

